# from sqlalchemy import Column,Integer,String,DateTime,Boolean,ForeignKey,CheckConstraint,    JSON
# from sqlalchemy.orm import relationship
# from datetime import datetime
# from app.db.database import Base
# from sqlalchemy.sql import func


# class WorkoutPlan(Base):
#     __tablename__ = "workout_plans"

#     id = Column(Integer, primary_key=True, index=True)
#     user_id = Column(
#         Integer,
#         ForeignKey("user_onboardings.id", ondelete="CASCADE"),
#         nullable=False,
#         index=True,
#     )
#     plan_name = Column(String(100), nullable=True)
#     training_days_per_week = Column(Integer, nullable=False)
#     plan_data = Column(JSON, nullable=False)  # JSONB in PostgreSQL, JSON in SQLAlchemy
#     is_active = Column(Boolean, nullable=False, default=True)
#     created_at = Column(DateTime, nullable=False, default=datetime.utcnow)

#     # Constraint to ensure training_days_per_week > 0
#     __table_args__ = (
#         CheckConstraint(
#             "training_days_per_week > 0", name="check_training_days_positive"
#         ),
#     )

#     # Relationship to User
#     user = relationship("User", back_populates="workout_plans")


from sqlalchemy import (
    Column,
    Integer,
    String,
    DateTime,
    Boolean,
    ForeignKey,
    CheckConstraint,
    JSON,
)
from sqlalchemy.orm import relationship
from datetime import datetime
from app.db.database import Base


class WorkoutPlan(Base):
    __tablename__ = "workout_plans"

    id = Column(Integer, primary_key=True, index=True)

    user_id = Column(
        Integer,
        ForeignKey("user_onboardings.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    plan_name = Column(
        String(100),
        nullable=True,
        comment="Optional name like 'Beginner Full Body Plan'",
    )

    training_days_per_week = Column(
        Integer,
        nullable=False,
        comment="Number of active workout days per week",
    )

    total_days_in_week = Column(
        Integer,
        nullable=False,
        default=7,
        comment="Total days covered by the plan (usually 7)",
    )

    workout_plan_data = Column(
        JSON,
        nullable=False,
        comment="Complete weekly workout plan JSON generated by AI",
    )

    is_active = Column(
        Boolean,
        nullable=False,
        default=True,
        comment="Only one active plan per user",
    )

    created_at = Column(
        DateTime,
        nullable=False,
        default=datetime.utcnow,
    )

    updated_at = Column(
        DateTime,
        nullable=False,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
    )

    __table_args__ = (
        CheckConstraint(
            "training_days_per_week > 0",
            name="check_training_days_positive",
        ),
    )

    # Relationship
    user = relationship("User", back_populates="workout_plans")
